<?php

namespace Database\Seeders;

use App\Models\Category;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {

        Schema::disableForeignKeyConstraints();
        Category::truncate();

        Category::insert([
            // 1
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Eid-Collection',
        		'url' => 'eid-collection',
        		'description' => '<p>Coolest collection is available</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'eid-collection',
                'meta_keywords' => 'eid-collection',
                'meta_description' => 'eid-collection',
                'search_keywords' => 'eid-collection',
                'creator' => '1',
        		'slug' => 'eid-collection',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 2
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Shirt',
        		'url' => 'shirt',
        		'description' => '<p>Attractive shirts are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'shirt',
                'meta_keywords' => 'shirt',
                'meta_description' => 'shirt',
                'search_keywords' => 'shirt',
                'creator' => '1',
        		'slug' => 'shirt',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 3
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Formal-Shirt',
        		'url' => 'formal shirt',
        		'description' => '<p>Attractive formal shirts are avaialable</p>',
                'parent_id' => 2,
                'category_image' => null,
                'page_title' => 'formal-shirt',
                'meta_keywords' => 'formal-shirt',
                'meta_description' => 'formal-shirt',
                'search_keywords' => 'formal-shirt',
                'creator' => '1',
        		'slug' => 'formal-shirt',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 4
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Casual-Shirt',
        		'url' => 'casual shirt',
        		'description' => '<p>Attractive casual shirts are avaialable</p>',
                'parent_id' => 2,
                'category_image' => null,
                'page_title' => 'casual-shirt',
                'meta_keywords' => 'casual-shirt',
                'meta_description' => 'casual-shirt',
                'search_keywords' => 'casual-shirt',
                'creator' => '1',
        		'slug' => 'casual-shirt',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 5
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Blazer',
        		'url' => 'blazer',
        		'description' => '<p>Attractive blazers are avaialable</p>',
                'parent_id' => 2,
                'category_image' => null,
                'page_title' => 'blazer',
                'meta_keywords' => 'blazer',
                'meta_description' => 'blazer',
                'search_keywords' => 'blazer',
                'creator' => '1',
        		'slug' => 'blazer',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 6
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'T-Shirt',
        		'url' => 't-shirt',
        		'description' => '<p>Nice t-shirts are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 't-shirt',
                'meta_keywords' => 't-shirt',
                'meta_description' => 't-shirt',
                'search_keywords' => 't-shirt',
                'creator' => '1',
        		'slug' => 't-shirt',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 7
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Pant',
        		'url' => 'pant',
        		'description' => '<p>Nice pants are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'pant',
                'meta_keywords' => 'pant',
                'meta_description' => 'pant',
                'search_keywords' => 'pant',
                'creator' => '1',
        		'slug' => 'pant',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 8
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Denim',
        		'url' => 'denim',
        		'description' => '<p>Nice denims are avaialable</p>',
                'parent_id' => 7,
                'category_image' => null,
                'page_title' => 'denim',
                'meta_keywords' => 'denim',
                'meta_description' => 'denim',
                'search_keywords' => 'denim',
                'creator' => '1',
        		'slug' => 'denim',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 9
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Formal-Pant',
        		'url' => 'formal-pant',
        		'description' => '<p>Nice formal pants are avaialable</p>',
                'parent_id' => 7,
                'category_image' => null,
                'page_title' => 'formal-pant',
                'meta_keywords' => 'formal-pant',
                'meta_description' => 'formal-pant',
                'search_keywords' => 'formal-pant',
                'creator' => '1',
        		'slug' => 'formal-pant',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 10
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Chinos',
        		'url' => 'chinos',
        		'description' => '<p>Nice chinos are avaialable</p>',
                'parent_id' => 7,
                'category_image' => null,
                'page_title' => 'chinos',
                'meta_keywords' => 'chinos',
                'meta_description' => 'chinos',
                'search_keywords' => 'chinos',
                'creator' => '1',
        		'slug' => 'chinos',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 11
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Joggers',
        		'url' => 'joggers',
        		'description' => '<p>Nice joggers are avaialable</p>',
                'parent_id' => 7,
                'category_image' => null,
                'page_title' => 'joggers',
                'meta_keywords' => 'joggers',
                'meta_description' => 'joggers',
                'search_keywords' => 'joggers',
                'creator' => '1',
        		'slug' => 'joggers',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 12
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Relaxed-Trouser',
        		'url' => 'relaxed-trouser',
        		'description' => '<p>Nice relaxed-trousers are avaialable</p>',
                'parent_id' => 7,
                'category_image' => null,
                'page_title' => 'relaxed-trouser',
                'meta_keywords' => 'relaxed-trouser',
                'meta_description' => 'relaxed-trouser',
                'search_keywords' => 'relaxed-trouser',
                'creator' => '1',
        		'slug' => 'relaxed-trouser',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 13
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Polo',
        		'url' => 'polo',
        		'description' => '<p>Nice polos are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'polo',
                'meta_keywords' => 'polo',
                'meta_description' => 'polo',
                'search_keywords' => 'polo',
                'creator' => '1',
        		'slug' => 'polo',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 14
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Panjabi',
        		'url' => 'panjabi',
        		'description' => '<p>Nice panjabis are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'panjabi',
                'meta_keywords' => 'panjabi',
                'meta_description' => 'panjabi',
                'search_keywords' => 'panjabi',
                'creator' => '1',
        		'slug' => 'panjabi',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 15
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Pajama',
        		'url' => 'pajama',
        		'description' => '<p>Nice pajamas are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'pajama',
                'meta_keywords' => 'pajama',
                'meta_description' => 'pajama',
                'search_keywords' => 'pajama',
                'creator' => '1',
        		'slug' => 'pajama',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 16
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Waistcoats',
        		'url' => 'waistcoat',
        		'description' => '<p>Nice waistcoats are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'waistcoat',
                'meta_keywords' => 'waistcoat',
                'meta_description' => 'waistcoat',
                'search_keywords' => 'waistcoat',
                'creator' => '1',
        		'slug' => 'waistcoat',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 17
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Wedding-Collection',
        		'url' => 'wedding-collection',
        		'description' => '<p>Nice wedding-collections are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'wedding-collection',
                'meta_keywords' => 'wedding-collection',
                'meta_description' => 'wedding-collection',
                'search_keywords' => 'wedding-collection',
                'creator' => '1',
        		'slug' => 'wedding-collection',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 18
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Sherwani',
        		'url' => 'sherwani',
        		'description' => '<p>Nice sherwanis are avaialable</p>',
                'parent_id' => 17,
                'category_image' => null,
                'page_title' => 'sherwani',
                'meta_keywords' => 'sherwani',
                'meta_description' => 'sherwani',
                'search_keywords' => 'sherwani',
                'creator' => '1',
        		'slug' => 'sherwani',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 19
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Nagra',
        		'url' => 'nagra',
        		'description' => '<p>Nice nagras are avaialable</p>',
                'parent_id' => 17,
                'category_image' => null,
                'page_title' => 'nagra',
                'meta_keywords' => 'nagra',
                'meta_description' => 'nagra',
                'search_keywords' => 'nagra',
                'creator' => '1',
        		'slug' => 'nagra',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 20
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Saree',
        		'url' => 'saree',
        		'description' => '<p>Nice sarees are avaialable</p>',
                'parent_id' => 17,
                'category_image' => null,
                'page_title' => 'saree',
                'meta_keywords' => 'saree',
                'meta_description' => 'saree',
                'search_keywords' => 'saree',
                'creator' => '1',
        		'slug' => 'saree',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 21
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Winter',
        		'url' => 'winter',
        		'description' => '<p>Nice winter collections are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'winter',
                'meta_keywords' => 'winter',
                'meta_description' => 'winter',
                'search_keywords' => 'winter',
                'creator' => '1',
        		'slug' => 'winter',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 22
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Winter',
        		'url' => 'jacket',
        		'description' => '<p>Nice jacket collections are avaialable</p>',
                'parent_id' => 20,
                'category_image' => null,
                'page_title' => 'jacket',
                'meta_keywords' => 'jacket',
                'meta_description' => 'jacket',
                'search_keywords' => 'jacket',
                'creator' => '1',
        		'slug' => 'jacket',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 23
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Winter',
        		'url' => 'sweatshirts',
        		'description' => '<p>Nice sweatshirts collections are avaialable</p>',
                'parent_id' => 20,
                'category_image' => null,
                'page_title' => 'sweatshirts',
                'meta_keywords' => 'sweatshirts',
                'meta_description' => 'sweatshirts',
                'search_keywords' => 'sweatshirts',
                'creator' => '1',
        		'slug' => 'sweatshirts',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 24
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Winter',
        		'url' => 'full-sleeve-t-shirts',
        		'description' => '<p>Nice full-sleeve-t-Shirt collections are avaialable</p>',
                'parent_id' => 20,
                'category_image' => null,
                'page_title' => 'full-sleeve-t-shirts',
                'meta_keywords' => 'full-sleeve-t-shirts',
                'meta_description' => 'full-sleeve-t-shirts',
                'search_keywords' => 'full-sleeve-t-shirts',
                'creator' => '1',
        		'slug' => 'full-sleeve-t-shirts',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 25
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Full-Sleeve-Polo',
        		'url' => 'full-sleeve-polo',
        		'description' => '<p>Nice full-sleeve-polo collections are avaialable</p>',
                'parent_id' => 20,
                'category_image' => null,
                'page_title' => 'full-sleeve-polo',
                'meta_keywords' => 'full-sleeve-polo',
                'meta_description' => 'full-sleeve-polo',
                'search_keywords' => 'full-sleeve-polo',
                'creator' => '1',
        		'slug' => 'full-sleeve-polo',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 26
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Hoodie',
        		'url' => 'hoodie',
        		'description' => '<p>Nice hoodie collections are avaialable</p>',
                'parent_id' => 20,
                'category_image' => null,
                'page_title' => 'hoodie',
                'meta_keywords' => 'hoodie',
                'meta_description' => 'hoodie',
                'search_keywords' => 'hoodie',
                'creator' => '1',
        		'slug' => 'hoodie',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 27
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Accessories',
        		'url' => 'accessories',
        		'description' => '<p>Nice accessories collections are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'accessories',
                'meta_keywords' => 'accessories',
                'meta_description' => 'accessories',
                'search_keywords' => 'accessories',
                'creator' => '1',
        		'slug' => 'accessories',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 28
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Belt',
        		'url' => 'belt',
        		'description' => '<p>Nice belt collections are avaialable</p>',
                'parent_id' => 26,
                'category_image' => null,
                'page_title' => 'belt',
                'meta_keywords' => 'belt',
                'meta_description' => 'belt',
                'search_keywords' => 'belt',
                'creator' => '1',
        		'slug' => 'belt',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 29
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Wallet',
        		'url' => 'wallet',
        		'description' => '<p>Nice wallet collections are avaialable</p>',
                'parent_id' => 26,
                'category_image' => null,
                'page_title' => 'wallet',
                'meta_keywords' => 'wallet',
                'meta_description' => 'wallet',
                'search_keywords' => 'wallet',
                'creator' => '1',
        		'slug' => 'wallet',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 30
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Tie',
        		'url' => 'tie',
        		'description' => '<p>Nice tie collections are avaialable</p>',
                'parent_id' => 26,
                'category_image' => null,
                'page_title' => 'tie',
                'meta_keywords' => 'tie',
                'meta_description' => 'tie',
                'search_keywords' => 'tie',
                'creator' => '1',
        		'slug' => 'tie',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 31
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Socks',
        		'url' => 'socks',
        		'description' => '<p>Nice socks collections are avaialable</p>',
                'parent_id' => 26,
                'category_image' => null,
                'page_title' => 'socks',
                'meta_keywords' => 'socks',
                'meta_description' => 'socks',
                'search_keywords' => 'socks',
                'creator' => '1',
        		'slug' => 'socks',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 32
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Perfume',
        		'url' => 'perfume',
        		'description' => '<p>Nice perfume collections are avaialable</p>',
                'parent_id' => 26,
                'category_image' => null,
                'page_title' => 'perfume',
                'meta_keywords' => 'perfume',
                'meta_description' => 'perfume',
                'search_keywords' => 'perfume',
                'creator' => '1',
        		'slug' => 'perfume',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 33
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Mug',
        		'url' => 'mugs',
        		'description' => '<p>Nice mugs collections are avaialable</p>',
                'parent_id' => 26,
                'category_image' => null,
                'page_title' => 'mugs',
                'meta_keywords' => 'mugs',
                'meta_description' => 'mugs',
                'search_keywords' => 'mugs',
                'creator' => '1',
        		'slug' => 'mugs',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 34
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Ethnic-Wear',
        		'url' => 'ethnic-wear',
        		'description' => '<p>Nice ethnic-wear collections are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'ethnic-wear',
                'meta_keywords' => 'ethnic-wear',
                'meta_description' => 'ethnic-wear',
                'search_keywords' => 'ethnic-wear',
                'creator' => '1',
        		'slug' => 'ethnic-wear',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 35
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Kids',
        		'url' => 'kids',
        		'description' => '<p>Nice kids collections are avaialable</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => 'kids',
                'meta_keywords' => 'kids',
                'meta_description' => 'kids',
                'search_keywords' => 'kids',
                'creator' => '1',
        		'slug' => 'kids',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 36
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Newborn',
        		'url' => 'newborn',
        		'description' => '<p>Nice newborn collections are avaialable</p>',
                'parent_id' => 34,
                'category_image' => null,
                'page_title' => 'newborn',
                'meta_keywords' => 'newborn',
                'meta_description' => 'newborn',
                'search_keywords' => 'newborn',
                'creator' => '1',
        		'slug' => 'newborn',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],

        ]);

        Schema::enableForeignKeyConstraints();
    }
}
