<?php

namespace Database\Seeders;

use App\Models\Product;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Schema::disableForeignKeyConstraints();
        Product::truncate();

        Product::insert([
            // 1
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 0,
		        'product_name' => "Classic Blue Printed Casual Shirt",
		        'product_url' => Str::slug('Classic Blue Printed Casual Shirt'),
		        'brand_id' => 1,
                'selected_categories' => "[1, 2]",
                'short_description' => "<ul><li>Material composition: 100% Cotton</li><li>Style: casual</li><li>Care: wash with similar color, wash, do not bleach, and do not tumble dry.</li><li>Iron: iron at maximum of 110ºc/230ºf.</li><li><b>product color may slightly vary due to photographic lighting.</b></li><li>Take good care of it.</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2139.90,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Classic Blue Printed Casual Shirt",
                'search_keywords' => "Classic Blue Printed Casual Shirt",
                'meta_description' => "Classic Blue Printed Casual Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => 'classic-blue-printed-casual-shirt',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 2
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 0,
		        'product_name' => "Men’s White Color Black Striped Polo Shirt",
		        'product_url' => Str::slug('Men’s White Color Black Striped Polo Shirt'),
		        'brand_id' => 1,
                'selected_categories' => "[1, 6, 13]",
                'short_description' => "<ul><li>Material composition: 95% Polyester &amp; 5% Spandex</li><li>Style: casual</li><li>Care: wash with similar color, wash, do not bleach, and do not tumble dry.</li><li>Iron: iron at maximum of 110ºc/230ºf.</li><li><b>product color may slightly vary due to photographic lighting.</b></li><li>Take good care of it.</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 1611.75,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s White Color Black Striped Polo Shirt",
                'search_keywords' => "Men’s White Color Black Striped Polo Shirt",
                'meta_description' => "Men’s White Color Black Striped Polo Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => 'men’s-white-color-black-striped-polo-shirt',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 3
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 0,
		        'product_name' => "Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt",
		        'product_url' => Str::slug('Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt'),
		        'brand_id' => 1,
                'selected_categories' => "[1, 2, 3]",
                'short_description' => "<ul><li>95% Cotton &amp; 5% Elastin</li><li>Slim-Fit</li><li>Available in sizes S to XXL</li><li>Ash Color</li><li>Suitable for all occasions.</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2921.10,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt",
                'search_keywords' => "Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt",
                'meta_description' => "Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "men’s-ash-color-cotton-full-sleeve-slim-fit-formal-shirt",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 4
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Premium Black Formal Pant",
		        'product_url' => Str::slug('Premium Black Formal Pant'),
		        'brand_id' => 1,
                'selected_categories' => "[1, 7]",
                'short_description' => "<p>Colour: Black<br>Fabric: Blended<br>Care: Dry Clean Only.<br>The model is wearing a size 32</p>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2783.55,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Black Formal Pant",
                'search_keywords' => "Premium Black Formal Pant",
                'meta_description' => "Premium Black Formal Pant",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => 'premium-black-formal-pant',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 5
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Richman Men’s White Striped Half Sleeve Round Neck T-Shirt",
		        'product_url' => Str::slug('Richman Men’s White Striped Half Sleeve Round Neck T-Shirt'),
		        'brand_id' => 1,
                'selected_categories' => "[1, 6]",
                'short_description' => "<ul><li>Fabrics: 100% Cotton</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 928.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Richman Men’s White Striped Half Sleeve Round Neck T-Shirt",
                'search_keywords' => "Richman Men’s White Striped Half Sleeve Round Neck T-Shirt",
                'meta_description' => "Richman Men’s White Striped Half Sleeve Round Neck T-Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "richman-men’s-white-striped-half-sleeve-round-neck-tShirt",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 6
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt",
		        'product_url' => Str::slug('Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt'),
		        'brand_id' => 1,
                'selected_categories' => "[2, 3]",
                'short_description' => "<ul><li>100% Cotton</li><li>Regular Fit</li><li>Available in sizes S to XXL</li><li>Sky Color</li><li>Suitable for all occasions.</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 3409.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'search_keywords' => "Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'meta_description' => "Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "men’s-sky-color-full-sleeve-cotton-regular-fit-formal-shirt",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 7
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt",
		        'product_url' => Str::slug('Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt'),
		        'brand_id' => 1,
                'selected_categories' => "[2, 3]",
                'short_description' => "<ul><li>100% Cotton</li><li>Regular Fit</li><li>Available in sizes S to XXL</li><li>Black Color</li><li>Suitable for all occasions.</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2588.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'search_keywords' => "Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'meta_description' => "Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "men’s-black-color-full-sleeve-cotton-regular-fit-formal-shirt",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 8
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Premium Black Check Blazer",
		        'product_url' => Str::slug('Premium Black Check Blazer'),
		        'brand_id' => 6,
                'selected_categories' => "[1, 2, 5]",
                'short_description' => "<ul><li>Dry wash only</li><li>Do not Bleach, and Do not tumble dry.</li><li>Iron at a maximum of 110ºc/230ºf.</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 6827.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Black Check Blazer",
                'search_keywords' => "Premium Black Check Blazer",
                'meta_description' => "Premium Black Check Blazer",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "premium-black-check-blazer",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 9
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Khaki Color Slim-fit Blazer",
		        'product_url' => Str::slug('Men’s Khaki Color Slim-fit Blazer'),
		        'brand_id' => 1,
                'selected_categories' => "[2, 5]",
                'short_description' => "<ul><li>Dry wash only</li><li>Do not Bleach, and Do not tumble dry.</li><li>Iron at a maximum of 110ºc/230ºf.</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 7472.09,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Khaki Color Slim-fit Blazer",
                'search_keywords' => "Men’s Khaki Color Slim-fit Blazer",
                'meta_description' => "Men’s Khaki Color Slim-fit Blazer",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "men’s-khaki-color-slim-fit-blazer",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 10
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Blue Color Slim-fit Blazer",
		        'product_url' => Str::slug('Men’s Blue Color Slim-fit Blazer'),
		        'brand_id' => 1,
                'selected_categories' => "[2, 5]",
                'short_description' => "<ul><li>Dry wash only</li><li>Do not Bleach, and Do not tumble dry.</li><li>Iron at a maximum of 110ºc/230ºf.</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 7472.09,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Blue Color Slim-fit Blazer",
                'search_keywords' => "Men’s Blue Color Slim-fit Blazer",
                'meta_description' => "Men’s Blue Color Slim-fit Blazer",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "men’s-blue-color-slim-fit-blazer",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 11
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt",
		        'product_url' => Str::slug('Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt'),
		        'brand_id' => 1,
                'selected_categories' => "[1, 6]",
                'short_description' => "<ul><li>Fabrics: 95% Cotton &amp; 5% Spandex</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 1025.85,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt",
                'search_keywords' => "Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt",
                'meta_description' => "Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "richman-men’s-olive-color-half-sleeve-round-neck-tShirt",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 12
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Coconut Tree Theme comfy T-shirt",
		        'product_url' => Str::slug('Coconut Tree Theme comfy T-shirt'),
		        'brand_id' => 1,
                'selected_categories' => "[1, 6]",
                'short_description' => "<ul><li>Fabrics: 95% Cotton &amp; 5% Spandex</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 967.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Coconut Tree Theme comfy T-shirt",
                'search_keywords' => "Coconut Tree Theme comfy T-shirt",
                'meta_description' => "Coconut Tree Theme comfy T-shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "coconut-tree-theme-comfy-tshirt",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 13
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Olive Color Solid Half Sleeve Polo Shirt",
		        'product_url' => Str::slug('Olive Color Solid Half Sleeve Polo Shirt'),
		        'brand_id' => 3,
                'selected_categories' => "[13]",
                'short_description' => "<ul><li>Fabrics: 95% Cotton &amp; 5% Spandex</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 1416.45,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Olive Color Solid Half Sleeve Polo Shirt",
                'search_keywords' => "Olive Color Solid Half Sleeve Polo Shirt",
                'meta_description' => "Olive Color Solid Half Sleeve Polo Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "olive-color-solid-half-sleeve-polo-shirt",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 14
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Coffee Color Printed Half Sleeve Polo Shirt",
		        'product_url' => Str::slug('Coffee Color Printed Half Sleeve Polo Shirt'),
		        'brand_id' => 3,
                'selected_categories' => "[1, 13]",
                'short_description' => "<ul><li>Fabrics: 95% Cotton &amp; 5% Spandex</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 1318.80,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Coffee Color Printed Half Sleeve Polo Shirt",
                'search_keywords' => "Coffee Color Printed Half Sleeve Polo Shirt",
                'meta_description' => "Coffee Color Printed Half Sleeve Polo Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "coffee-color-printed-half-sleeve-polo-shirt",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 15
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Premium Black Color Denim",
		        'product_url' => Str::slug('Premium Black Color Denim'),
		        'brand_id' => 2,
                'selected_categories' => "[7, 8]",
                'short_description' => "<ul><li><p>Slim-fit jeans. Five pockets. Faded effect. Zip fly and button fastening on the front.</p></li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2392.95,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Black Color Denim",
                'search_keywords' => "Premium Black Color Denim",
                'meta_description' => "Premium Black Color Denim",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "premium-black-color-denim",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 16
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Dark Blue color Denim Pant",
		        'product_url' => Str::slug('Men’s Dark Blue color Denim Pant'),
		        'brand_id' => 2,
                'selected_categories' => "[7, 8]",
                'short_description' => "<ul><li><p>Slim-fit jeans. Five pockets. Faded effect. Zip fly and button fastening on the front.</p></li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2724.75,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Dark Blue color Denim Pant",
                'search_keywords' => "Men’s Dark Blue color Denim Pant",
                'meta_description' => "Men’s Dark Blue color Denim Pant",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "men’s-dark-blue-color-denim-pant",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 17
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Premium Black Formal Pant",
		        'product_url' => Str::slug('Premium Black Formal Pant'),
		        'brand_id' => 4,
                'selected_categories' => "[1, 7, 9]",
                'short_description' => "<ul><li><p>Slim-fit. two pockets. Faded effect. Zip fly and button fastening on the front.The model is wearing a size 32</p></li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2783.55,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Black Formal Pant",
                'search_keywords' => "Premium Black Formal Pant",
                'meta_description' => "Premium Black Formal Pant",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "premium-black-formal-pant",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 18
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Premium Grey Colour Slim Fit Formal Pant",
		        'product_url' => Str::slug('Premium Grey Colour Slim Fit Formal Pant'),
		        'brand_id' => 4,
                'selected_categories' => "[1, 7, 9]",
                'short_description' => "<ul><li><p>Slim-fit. two pockets. Faded effect. Zip fly and button fastening on the front.The model is wearing a size 32</p></li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2920.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Grey Colour Slim Fit Formal Pant",
                'search_keywords' => "Premium Grey Colour Slim Fit Formal Pant",
                'meta_description' => "Premium Grey Colour Slim Fit Formal Pant",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "premium-grey-colour-slim-fit-formal-pant",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 19
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Smart Shape Black Color Premium Gabardine Pant",
		        'product_url' => Str::slug('Men’s Smart Shape Black Color Premium Gabardine Pant'),
		        'brand_id' => 4,
                'selected_categories' => "[1, 7, 10]",
                'short_description' => "<ul><li><p>Slim-fit. two pockets. Faded effect. Zip fly and button fastening on the front.The model is wearing a size 32</p></li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2588.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Smart Shape Black Color Premium Gabardine Pant",
                'search_keywords' => "Men’s Smart Shape Black Color Premium Gabardine Pant",
                'meta_description' => "Men’s Smart Shape Black Color Premium Gabardine Pant",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "men’s-smart-shape-black-color-premium-gabardine-pant",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 20
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Premium Slim Fit twill Pant",
		        'product_url' => Str::slug('Premium Slim Fit twill Pant'),
		        'brand_id' => 4,
                'selected_categories' => "[1, 7, 10]",
                'short_description' => "<ul><li><p>Slim fit pant made of stretchy cotton fabric. Featuring front pockets, rear pockets and zip fly and top button fastening.</p></li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 2920.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Slim Fit twill Pant",
                'search_keywords' => "Premium Slim Fit twill Pant",
                'meta_description' => "Premium Slim Fit twill Pant",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "premium-slim-fit-twill-pant",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 21
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Classic White Knit Joggers",
		        'product_url' => Str::slug('Classic White Knit Joggers'),
		        'brand_id' => 5,
                'selected_categories' => "[7, 11]",
                'short_description' => "<ul><li><p><strong>Material composition :<br>100% Polyester&nbsp;</strong></p></li><li><p><strong>Style &amp; Fit</strong><br>Slim fit, Sports Wear.</p></li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 1807.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Classic White Knit Joggers",
                'search_keywords' => "Classic White Knit Joggers",
                'meta_description' => "Classic White Knit Joggers",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => "classic-white-knit-joggers",
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 22
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Classic Ash Color Jogger",
		        'product_url' => Str::slug('Classic Ash Color Jogger'),
		        'brand_id' => 5,
                'selected_categories' => "[1, 7, 11]",
                'short_description' => "<ul><li>60% Cotton &amp; 40 % Polyester.</li><li>Machine wash up to 30°c/86°f gentle cycle</li><li>Do not bleach</li><li>Iron up to 110°c/230°f</li><li>Do not iron directly on prints/embroidery/embellishments</li><li>Do not dry clean</li><li>Do not tumble dry.<br></li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 1416.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Classic Ash Color Jogger",
                'search_keywords' => "Classic Ash Color Jogger",
                'meta_description' => "Classic Ash Color Jogger",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Classic Ash Color Jogger"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 23
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Mens Cream Colour Luxury Panjabi set",
		        'product_url' => Str::slug('Mens Cream Colour Luxury Panjabi set'),
		        'brand_id' => 6,
                'selected_categories' => "[1, 14]",
                'short_description' => "<ul><li>Indian Cotton</li><li>Regular Fit</li><li>Cream Colour</li></ul><p>PANJABI made with high-quality fabrics and exquisite embellishments. It is usually priced at a premium and is designed for customers who are looking for something unique and exclusive.</p>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 8351.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Mens Cream Colour Luxury Panjabi set",
                'search_keywords' => "Mens Cream Colour Luxury Panjabi set",
                'meta_description' => "Mens Cream Colour Luxury Panjabi set",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Mens Cream Colour Luxury Panjabi set"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 24
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Maroon Colour Luxury Panjabi set",
		        'product_url' => Str::slug('Men’s Maroon Colour Luxury Panjabi set'),
		        'brand_id' => 6,
                'selected_categories' => "[1, 14]",
                'short_description' => "<ul><li>Indian Cotton</li><li>Regular Fit</li><li>Maroon  Colour</li></ul><p>PANJABI made with high-quality fabrics and exquisite embellishments. It is usually priced at a premium and is designed for customers who are looking for something unique and exclusive.</p>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 7032.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Maroon Colour Luxury Panjabi set",
                'search_keywords' => "Men’s Maroon Colour Luxury Panjabi set",
                'meta_description' => "Men’s Maroon Colour Luxury Panjabi set",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Men’s Maroon Colour Luxury Panjabi set"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 25
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Luxury Dark Olive Colour Panjabi",
		        'product_url' => Str::slug('Luxury Dark Olive Colour Panjabi'),
		        'brand_id' => 7,
                'selected_categories' => "[14]",
                'short_description' => "<ul><li>Indian Cotton</li><li>Regular Fit</li><li>Dark Olive  Colour</li></ul><p>PANJABI made with high-quality fabrics and exquisite embellishments. It is usually priced at a premium and is designed for customers who are looking for something unique and exclusive.</p>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 12942.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Luxury Dark Olive Colour Panjabi",
                'search_keywords' => "Luxury Dark Olive Colour Panjabi",
                'meta_description' => "Luxury Dark Olive Colour Panjabi",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Luxury Dark Olive Colour Panjabi"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 26
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Regular Fit Sky Color",
		        'product_url' => Str::slug('Men’s Regular Fit Sky Color'),
		        'brand_id' => 7,
                'selected_categories' => "[14]",
                'short_description' => "<ul><li>Indian Cotton</li><li>Regular Fit</li><li>Sky  Colour</li></ul><p>PANJABI made with high-quality fabrics and exquisite embellishments. It is usually priced at a premium and is designed for customers who are looking for something unique and exclusive.</p>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 3564.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Regular Fit Sky Color",
                'search_keywords' => "Men’s Regular Fit Sky Color",
                'meta_description' => "Men’s Regular Fit Sky Color",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Men’s Regular Fit Sky Color"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 27
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Premium Slim-Fit Pajama",
		        'product_url' => Str::slug('Premium Slim-Fit Pajama'),
		        'brand_id' => 8,
                'selected_categories' => "[1, 15]",
                'short_description' => "<ul><li><p>Material: 98% Cotton 2% Spandex<br>FIT: Slim-Fit</p></li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 1260.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Slim-Fit Pajama",
                'search_keywords' => "Premium Slim-Fit Pajama",
                'meta_description' => "Premium Slim-Fit Pajama",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Premium Slim-Fit Pajama"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 28
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men\’s Maroon Color Bridal Sherwani with Pajama",
		        'product_url' => Str::slug('Men\’s Maroon Color Bridal Sherwani with Pajama'),
		        'brand_id' => 9,
                'selected_categories' => "[15, 17, 18]",
                'short_description' => "<ul><li>Fit: Tailored Fit</li><li>Color: Fancy Maroon</li><li>Fabric: Blended</li><li>Occasion: Wedding</li><li>Neck: Mandarin Collar</li><li>Sleeve: Full Sleeve</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 21976.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men\’s Maroon Color Bridal Sherwani with Pajama",
                'search_keywords' => "Men\’s Maroon Color Bridal Sherwani with Pajama",
                'meta_description' => "Men\’s Maroon Color Bridal Sherwani with Pajama",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Men\’s Maroon Color Bridal Sherwani with Pajama"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 29
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Maroon Color Bridal Sherwani with Pajama",
		        'product_url' => Str::slug('Maroon Color Bridal Sherwani with Pajama'),
		        'brand_id' => 9,
                'selected_categories' => "[15, 17, 18]",
                'short_description' => "<ul><li>Fit: Tailored Fit</li><li>Color: Fancy Maroon</li><li>Fabric: 100% POLYESTER</li><li>Occasion: Wedding</li><li>Neck: Mandarin Collar</li><li>Sleeve: Full Sleeve</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 11671.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Maroon Color Bridal Sherwani with Pajama",
                'search_keywords' => "Maroon Color Bridal Sherwani with Pajama",
                'meta_description' => "Maroon Color Bridal Sherwani with Pajama",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Maroon Color Bridal Sherwani with Pajama"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 30
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Blue Handloom Katan Saree",
		        'product_url' => Str::slug('Blue Handloom Katan Saree'),
		        'brand_id' => 10,
                'selected_categories' => "[1, 17, 20]",
                'short_description' => "<ul><li>Rare Saree</li><li>Eye Catching Color</li></ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 1970.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Blue Handloom Katan Saree",
                'search_keywords' => "Blue Handloom Katan Saree",
                'meta_description' => "Blue Handloom Katan Saree",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Blue Handloom Katan Saree"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 31
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Olive Green Muslin Embroidered & Karchupi Ornamented Saree",
		        'product_url' => Str::slug('Olive Green Muslin Embroidered & Karchupi Ornamented Saree'),
		        'brand_id' => 10,
                'selected_categories' => "[1, 17, 20]",
                'short_description' => "<ul>
                <li>Blouse shown in the photo, not a part of the actual product</li>
                <li>Comes with unstitched matching silk blouse piece</li>
                <li>This olive green muslin saree comes with balaka silk anchal</li>
                <li>Embellished with embroidery and karchupi</li>
                <li>Aanchal with trimmed Tassel</li>
                </ul>",
                'description' => "",
                'specification' => "",
                
                'image' => null,
                'cost' => null,
                'sales_price' => 19995.00,
                'call_for_price' => null,
                
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Olive Green Muslin Embroidered & Karchupi Ornamented Saree",
                'search_keywords' => "Olive Green Muslin Embroidered & Karchupi Ornamented Saree",
                'meta_description' => "Olive Green Muslin Embroidered & Karchupi Ornamented Saree",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Olive Green Muslin Embroidered & Karchupi Ornamented Saree"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],




        ]);


        Schema::enableForeignKeyConstraints();


    }
}
